### ISSUE TITLE
gyp build error

### ISSUE THREAD

**Issue by tellok** [andrewrk/mcserve#19]
```
# npm i mcserve -S
npm WARN deprecated connect@2.7.5: connect 2.x series is deprecated

> ursa@0.8.5 install /root/minecraft/node_modules/ursa
> node-gyp rebuild

make: Entering directory '/root/minecraft/node_modules/ursa/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
In file included from ../../nan/nan.h:111:0,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_new.h: In function 'v8::Local<T> Nan::imp::To(v8::Handle<v8::Integer>) [with T = v8::Int32; v8::Handle<v8::Integer> = v8::Local<v8::Integer>]':
../../nan/nan_new.h:34:64: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
 To<v8::Int32>(v8::Handle<v8::Integer> i)   { return i->ToInt32(); }
                                                                ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:9743:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
In file included from ../../nan/nan.h:111:0,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_new.h: In function 'v8::Local<T> Nan::imp::To(v8::Handle<v8::Integer>) [with T = v8::Uint32; v8::Handle<v8::Integer> = v8::Local<v8::Integer>]':
../../nan/nan_new.h:39:65: warning: 'v8::Local<v8::Uint32> v8::Value::ToUint32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
 To<v8::Uint32>(v8::Handle<v8::Integer> i)  { return i->ToUint32(); }
                                                                 ^
In file included from /root/.node-gyp/8.9.4/include/node/node.h:63:0,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:9737:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)':
../../nan/nan_implementation_12_inl.h:49:38: warning: 'static v8::Local<v8::Value> v8::BooleanObject::New(bool)' is deprecated: Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:4793:56: note: declared here
   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                        ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::Script>::return_t Nan::imp::Factory<v8::Script>::New(v8::Local<v8::String>)':
../../nan/nan_implementation_12_inl.h:166:69: warning: 'static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                                                                     ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:1424:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::Script>::return_t Nan::imp::Factory<v8::Script>::New(v8::Local<v8::String>, const v8::ScriptOrigin&)':
../../nan/nan_implementation_12_inl.h:173:69: warning: 'static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &src);
                                                                     ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:1424:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::String>::return_t Nan::imp::Factory<v8::String>::New(const uint8_t*, int)':
../../nan/nan_implementation_12_inl.h:206:42: warning: 'static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)' is deprecated: Use maybe version [-Wdeprecated-declarations]
         v8::String::kNormalString, length);
                                          ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:2670:21: note: declared here
       Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                     ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::String>::return_t Nan::imp::Factory<v8::String>::New(v8::String::ExternalStringResource*)':
../../nan/nan_implementation_12_inl.h:217:66: warning: 'static v8::Local<v8::String> v8::String::NewExternal(v8::Isolate*, v8::String::ExternalStringResource*)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::String::NewExternal(v8::Isolate::GetCurrent(), value);
                                                                  ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:2708:38: note: declared here
                        Local<String> NewExternal(
                                      ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::UnboundScript>::return_t Nan::imp::Factory<v8::UnboundScript>::New(v8::Local<v8::String>)':
../../nan/nan_implementation_12_inl.h:237:30: warning: 'static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                              ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:1404:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h:237:76: warning: 'static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                                                                            ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:1404:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::UnboundScript>::return_t Nan::imp::Factory<v8::UnboundScript>::New(v8::Local<v8::String>, const v8::ScriptOrigin&)':
../../nan/nan_implementation_12_inl.h:244:30: warning: 'static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                              ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:1404:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../../nan/nan_new.h:191:0,
                 from ../../nan/nan.h:111,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
../../nan/nan_implementation_12_inl.h:244:76: warning: 'static v8::Local<v8::UnboundScript> v8::ScriptCompiler::CompileUnbound(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)' is deprecated: Use maybe version [-Wdeprecated-declarations]
   return v8::ScriptCompiler::CompileUnbound(v8::Isolate::GetCurrent(), &src);
                                                                            ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:1404:45: note: declared here
                        Local<UnboundScript> CompileUnbound(
                                             ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/ursaNative.h:10:0,
                 from ../src/ursaNative.cc:3:
../../nan/nan.h: At global scope:
../../nan/nan.h:324:27: error: redefinition of 'template<class T> v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T>&)'
   NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                           ^
../../nan/nan.h:319:17: note: 'template<class T> v8::Handle<T> Nan::imp::NanEnsureHandleOrPersistent(v8::Handle<T>&)' previously declared here
   v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                 ^
../../nan/nan.h:344:27: error: redefinition of 'template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(v8::Handle<T>&)'
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                           ^
../../nan/nan.h:334:27: note: 'template<class T> v8::Local<T> Nan::imp::NanEnsureLocal(const v8::Local<T>&)' previously declared here
   NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                           ^
../../nan/nan.h: In function 'bool NanIdleNotification(int)':
../../nan/nan.h:374:71: warning: 'bool v8::Isolate::IdleNotification(int)' is deprecated: use IdleNotificationDeadline() [-Wdeprecated-declarations]
     return v8::Isolate::GetCurrent()->IdleNotification(idle_time_in_ms);
                                                                       ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:7429:22: note: declared here
                 bool IdleNotification(int idle_time_in_ms));
                      ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/ursaNative.h:10:0,
                 from ../src/ursaNative.cc:3:
../../nan/nan.h: At global scope:
../../nan/nan.h:560:20: error: variable or field 'NanAddGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:560:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:561:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:566:20: error: variable or field 'NanRemoveGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:566:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:571:20: error: variable or field 'NanAddGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:571:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:572:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:577:20: error: variable or field 'NanRemoveGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:577:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback) {
       ^
../../nan/nan.h:659:15: error: 'WeakCallbackData' in namespace 'v8' does not name a template type
     const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
               ^
../../nan/nan.h:659:31: error: expected ',' or '...' before '<' token
     const v8::WeakCallbackData<T, _NanWeakCallbackInfo<T, P> > &data) {
                               ^
../../nan/nan.h: In function 'void _NanWeakCallbackDispatcher(int)':
../../nan/nan.h:660:42: error: 'data' was not declared in this scope
       _NanWeakCallbackInfo<T, P> *info = data.GetParameter();
                                          ^
../../nan/nan.h: At global scope:
../../nan/nan.h:757:13: error: 'node::smalloc' has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:757:35: error: expected ',' or '...' before 'callback'
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)':
../../nan/nan.h:761:50: error: 'callback' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:761:60: error: 'hint' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)':
../../nan/nan.h:768:67: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../../nan/nan.h:25:0,
                 from ../src/ursaNative.h:10,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/node_buffer.h:67:40: note:   initializing argument 2 of 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t)'
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
In file included from ../src/ursaNative.h:10:0,
                 from ../src/ursaNative.cc:3:
../../nan/nan.h:768:29: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), ((char*)data), ((size_t)size))' from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                             ^
../../nan/nan.h: In function 'v8::Local<v8::Object> NanNewBufferHandle(uint32_t)':
../../nan/nan.h:772:29: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))' from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../../nan/nan.h: In function 'v8::Local<v8::Object> NanBufferUse(char*, uint32_t)':
../../nan/nan.h:779:12: error: 'Use' is not a member of 'node::Buffer'
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../../nan/nan.h: In function 'v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>, const v8::ScriptOrigin&)':
../../nan/nan.h:806:74: warning: 'static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:1424:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/ursaNative.h:10:0,
                 from ../src/ursaNative.cc:3:
../../nan/nan.h: In function 'v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>)':
../../nan/nan.h:813:74: warning: 'static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../src/ursaNative.h:9,
                 from ../src/ursaNative.cc:3:
/root/.node-gyp/8.9.4/include/node/v8.h:1424:21: note: declared here
       Local<Script> Compile(Isolate* isolate, Source* source,
                     ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
ursaNative.target.mk:98: recipe for target 'Release/obj.target/ursaNative/src/ursaNative.o' failed
make: *** [Release/obj.target/ursaNative/src/ursaNative.o] Error 1
make: Leaving directory '/root/minecraft/node_modules/ursa/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-105-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/minecraft/node_modules/ursa
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN minecraft@1.0.0 No description
npm WARN minecraft@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.8.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-18T06_30_07_418Z-debug.log
```

**Comment by Maks1116** [comment]
This project is very very old and nobody touched it since minecraft 1.5. Nobody will help you with this, as it seems to be error with old and deprecated library

**Comment by tellok** [comment]
> This project is very very old and nobody touched it since minecraft 1.5. Nobody will help you with this, as it seems to be error with old and deprecated library

thank you for your kinda reply

**Comment by rom1504** [comment]
If you do want it to work, it would definitely be possible to update it.
The underlying libraries (node-minecraft-protocol and mineflayer) are still
maintained.

Would need a bit of work to update the dependencies here and check what
need to be updated.
